create extension if not exists "pgcrypto";
create table public.users (id uuid primary key default gen_random_uuid(), full_name text not null check (char_length(full_name) between 2 and 100), email text unique not null, password_hash text not null, monthly_allowance numeric(12,2) not null default 0 check(monthly_allowance >= 0), currency text not null default 'INR', reset_token_hash text, reset_token_expires timestamptz, created_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), name text unique not null, icon text, color text, is_default boolean not null default true);
create table public.expenses (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, title text not null check(char_length(title) between 1 and 100), amount numeric(12,2) not null check(amount > 0), category_id uuid not null references public.categories(id), payment_method text not null, expense_date date not null, description text default '', is_recurring boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.budgets (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, category_id uuid references public.categories(id), monthly_limit numeric(12,2) not null check(monthly_limit > 0), month date not null, created_at timestamptz not null default now(), unique(user_id,category_id,month));
create table public.savings_goals (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, title text not null, target_amount numeric(12,2) not null check(target_amount > 0), current_amount numeric(12,2) not null default 0 check(current_amount >= 0), target_date date, created_at timestamptz not null default now());
create table public.financial_insights (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, insight_type text not null, message text not null, created_at timestamptz not null default now());
create index expenses_user_date_idx on public.expenses(user_id,expense_date desc); create index budgets_user_month_idx on public.budgets(user_id,month); create index goals_user_idx on public.savings_goals(user_id);
insert into public.categories(name,icon,color) values ('Food','Utensils','#f97316'),('Transportation','Bus','#3b82f6'),('Education','BookOpen','#8b5cf6'),('Entertainment','Film','#ec4899'),('Shopping','ShoppingBag','#14b8a6'),('Gaming','Gamepad2','#6366f1'),('Mobile Recharge','Smartphone','#06b6d4'),('Personal Care','Heart','#f43f5e'),('Health','Cross','#22c55e'),('Savings','PiggyBank','#10b981'),('Other','Circle','#64748b');
-- The backend uses the service-role key and enforces ownership server-side. Enable RLS before exposing direct client access.
alter table public.users enable row level security; alter table public.expenses enable row level security; alter table public.budgets enable row level security; alter table public.savings_goals enable row level security; alter table public.financial_insights enable row level security;
