import bcrypt from 'bcrypt'; import jwt from 'jsonwebtoken'; import crypto from 'crypto'; import { supabase } from '../config/supabase.js'; import { AppError } from '../utils/AppError.js';
const safe = ({ password_hash, ...user }) => user;
const tokenFor = (user) => jwt.sign({ id: user.id, email: user.email }, process.env.JWT_SECRET, { expiresIn: '7d' });
const respond = (res, user, status = 200) => { const token = tokenFor(user); res.cookie('token', token, { httpOnly: true, sameSite: 'lax', secure: process.env.NODE_ENV === 'production', maxAge: 604800000 }); res.status(status).json({ success: true, data: { user: safe(user), token } }); };
export async function register(req, res, next) { try { const { fullName, email, password, monthlyAllowance = 0, currency = 'INR' } = req.body; const { data: existing } = await supabase.from('users').select('id').eq('email', email.toLowerCase()).maybeSingle(); if (existing) throw new AppError('Unable to create account with these details', 409); const password_hash = await bcrypt.hash(password, 12); const { data, error } = await supabase.from('users').insert({ full_name: fullName.trim(), email: email.toLowerCase(), password_hash, monthly_allowance: monthlyAllowance, currency }).select().single(); if (error) throw error; respond(res, data, 201); } catch (e) { next(e); } }
export async function login(req, res, next) { try { const { email, password } = req.body; const { data: user, error } = await supabase.from('users').select('*').eq('email', email.toLowerCase()).maybeSingle(); if (error || !user || !(await bcrypt.compare(password, user.password_hash))) throw new AppError('Invalid email or password', 401); respond(res, user); } catch (e) { next(e); } }
export async function me(req, res, next) { try { const { data, error } = await supabase.from('users').select('id,full_name,email,monthly_allowance,currency,created_at').eq('id', req.user.id).single(); if (error) throw error; res.json({ success: true, data }); } catch (e) { next(e); } }
export const logout = (_req, res) => { res.clearCookie('token'); res.json({ success: true, message: 'Logged out successfully' }); };
export async function requestPasswordReset(req,res,next){try{const email=req.body.email.toLowerCase();const {data:user}=await supabase.from('users').select('id').eq('email',email).maybeSingle();if(user){const token=crypto.randomBytes(32).toString('hex'),hash=crypto.createHash('sha256').update(token).digest('hex');await supabase.from('users').update({reset_token_hash:hash,reset_token_expires:new Date(Date.now()+3600000).toISOString()}).eq('id',user.id);if(process.env.NODE_ENV==='development') return res.json({success:true,message:'If an account exists, reset instructions have been created.',data:{resetToken:token}});}res.json({success:true,message:'If an account exists, reset instructions have been sent.'});}catch(e){next(e)}}
export async function resetPassword(req,res,next){try{const hash=crypto.createHash('sha256').update(req.params.token).digest('hex');const {data:user}=await supabase.from('users').select('id').eq('reset_token_hash',hash).gt('reset_token_expires',new Date().toISOString()).maybeSingle();if(!user)throw new AppError('This reset link is invalid or has expired',400);const password_hash=await bcrypt.hash(req.body.password,12);const {error}=await supabase.from('users').update({password_hash,reset_token_hash:null,reset_token_expires:null}).eq('id',user.id);if(error)throw error;res.json({success:true,message:'Password reset successfully'});}catch(e){next(e)}}
