import { supabase } from '../config/supabase.js'; import { AppError } from '../utils/AppError.js'; import { generateInsights } from '../services/insightsService.js'; import { monthBounds } from '../utils/financial.js';
export const categories=async(_req,res,next)=>{try{const {data,error}=await supabase.from('categories').select('*').order('name');if(error)throw error;res.json({success:true,data});}catch(e){next(e)}};
const config={budgets:{table:'budgets',fields:['category_id','monthly_limit','month']},savings:{table:'savings_goals',fields:['title','target_amount','current_amount','target_date']}};
const handler=(type)=>({
 list:async(req,res,next)=>{try{const {data,error}=await supabase.from(config[type].table).select('*,categories(name,color)').eq('user_id',req.user.id).order('created_at',{ascending:false});if(error)throw error;res.json({success:true,data});}catch(e){next(e)}},
 create:async(req,res,next)=>{try{const fields=config[type].fields, row={user_id:req.user.id};fields.forEach(f=>{if(req.body[f]!==undefined)row[f]=req.body[f]});const {data,error}=await supabase.from(config[type].table).insert(row).select('*,categories(name,color)').single();if(error)throw error;res.status(201).json({success:true,data});}catch(e){next(e)}},
 update:async(req,res,next)=>{try{const fields=config[type].fields, row={};fields.forEach(f=>{if(req.body[f]!==undefined)row[f]=req.body[f]});const {data,error}=await supabase.from(config[type].table).update(row).eq('id',req.params.id).eq('user_id',req.user.id).select('*,categories(name,color)').maybeSingle();if(error)throw error;if(!data)throw new AppError('Record not found',404);res.json({success:true,data});}catch(e){next(e)}},
 remove:async(req,res,next)=>{try{const {data,error}=await supabase.from(config[type].table).delete().eq('id',req.params.id).eq('user_id',req.user.id).select('id').maybeSingle();if(error)throw error;if(!data)throw new AppError('Record not found',404);res.json({success:true,message:'Deleted successfully'});}catch(e){next(e)}}
});
export const budgets=handler('budgets'); export const savings=handler('savings');
export const contribution=async(req,res,next)=>{try{const amount=Number(req.body.amount);if(!Number.isFinite(amount)||amount<=0)throw new AppError('Contribution must be greater than zero',422);const {data:goal}=await supabase.from('savings_goals').select('*').eq('id',req.params.id).eq('user_id',req.user.id).maybeSingle();if(!goal)throw new AppError('Savings goal not found',404);const {data,error}=await supabase.from('savings_goals').update({current_amount:Number(goal.current_amount)+amount}).eq('id',goal.id).select().single();if(error)throw error;res.json({success:true,data});}catch(e){next(e)}};
export const insights=async(req,res,next)=>{try{const {start,end}=monthBounds();const [ex,u,b]=await Promise.all([supabase.from('expenses').select('amount,category_id,categories(name)').eq('user_id',req.user.id).gte('expense_date',start).lt('expense_date',end),supabase.from('users').select('monthly_allowance').eq('id',req.user.id).single(),supabase.from('budgets').select('*,categories(name)').eq('user_id',req.user.id).eq('month',start)]);if(ex.error)throw ex.error;res.json({success:true,data:generateInsights({expenses:ex.data,allowance:u.data.monthly_allowance,budgets:b.data,previousTotal:0})});}catch(e){next(e)}};
